import{a as d}from"./assets/vendor-a61d8330.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const g="live_SOQUwbBJp7SdKrG9q4yg98wu5COkSubVNkG7GRxEQDaqsolCd1Ia5dgduy4S0u92";d.defaults.headers.common["x-api-key"]=g;const h=async()=>(await d.get("https://api.thecatapi.com/v1/breeds")).data,b=async t=>(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`)).data,s=document.querySelector(".breed-select"),y=document.querySelector(".loader"),p=document.querySelector(".error"),a=document.querySelector(".cat-info"),S=async()=>{try{(await h()).forEach(o=>{const r=document.createElement("option");r.value=o.id,r.text=o.name,s.add(r)})}catch{m()}finally{f()}},x=async t=>{try{const r=(await b(t))[0],c=`
      <div class="cat-info-container">
        <img src="${r.url}" alt="${r.breeds[0].name}" class="cat-image">
        <div class="cat-text">
          <p><strong>Breed:</strong> ${r.breeds[0].name}</p>
          <p><strong>Description:</strong> ${r.breeds[0].description}</p>
          <p><strong>Temperament:</strong> ${r.breeds[0].temperament}</p>
        </div>
      </div>
    `;a.innerHTML=c,v(),i()}catch{m()}finally{f()}},v=()=>{const t=document.querySelector(".cat-info-container"),o=t.querySelector(".cat-image"),r=t.querySelector(".cat-text");s.style.marginBottom="10px",t.style.display="flex",t.style.flexWrap="wrap",o.style.maxWidth="400px",o.style.marginRight="20px",r.style.flex="1"},u=()=>{y.style.display="block",s.style.display="none",a.style.display="none",i()},f=()=>{y.style.display="none",s.style.display="block",a.style.display="block"},m=()=>{p.style.display="block",s.style.display="none",a.style.display="none",a.innerHTML=""},i=()=>{p.style.display="none"};s.addEventListener("change",async t=>{const o=t.target.value;u(),i(),await x(o)});document.addEventListener("DOMContentLoaded",()=>{u(),i(),S()});
//# sourceMappingURL=commonHelpers.js.map
