import{a}from"./assets/vendor-a61d8330.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const m="live_SOQUwbBJp7SdKrG9q4yg98wu5COkSubVNkG7GRxEQDaqsolCd1Ia5dgduy4S0u92";a.defaults.headers.common["x-api-key"]=m;const h=async()=>{try{return(await a.get("https://api.thecatapi.com/v1/breeds")).data}catch(e){throw e}},g=async e=>{try{return(await a.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`)).data}catch(t){throw t}},i=document.querySelector(".breed-select"),d=document.querySelector(".loader"),l=document.querySelector(".error"),b=document.querySelector(".cat-info"),S=async()=>{try{(await h()).forEach(t=>{const o=document.createElement("option");o.value=t.id,o.text=t.name,i.add(o)})}catch{y()}finally{p()}},x=async e=>{try{const o=(await g(e))[0],s=`
      <div class="cat-info-container">
        <img src="${o.url}" alt="${o.breeds[0].name}" class="cat-image">
        <div class="cat-text">
          <p><strong>Breed:</strong> ${o.breeds[0].name}</p>
          <p><strong>Description:</strong> ${o.breeds[0].description}</p>
          <p><strong>Temperament:</strong> ${o.breeds[0].temperament}</p>
        </div>
      </div>
    `;b.innerHTML=s,v()}catch{y()}finally{p()}},v=()=>{const e=document.querySelector(".cat-info-container"),t=e.querySelector(".cat-image"),o=e.querySelector(".cat-text");i.style.marginBottom="10px",e.style.display="flex",e.style.flexWrap="wrap",t.style.maxWidth="400px",t.style.marginRight="20px",o.style.flex="1"},u=()=>{d.style.display="block"},p=()=>{d.style.display="none"},y=()=>{l.style.display="block"},f=()=>{l.style.display="none"};i.addEventListener("change",e=>{const t=e.target.value;u(),f(),x(t)});document.addEventListener("DOMContentLoaded",()=>{u(),f(),S()});
//# sourceMappingURL=commonHelpers.js.map
